name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-format-lint:
    name: Format + Lint (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Format
        run: cargo fmt --all --check
      - name: Lint
        run: cargo clippy --all -- -D warnings

  python-format-lint:
    name: Format + Lint (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Format
        run: uvx ruff format . --check
      - name: Lint
        run: uvx ruff check .

  test:
    name: Test (Python ${{ matrix.python_version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.12', '3.13']
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
      - name: Install Dependencies
        run: pip install -r ./tests/requirements.txt
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test -F ci


